### ISSUE TITLE
Correct calculation of cpu frequency

### ISSUE THREAD

**Issue by UllusParvus** [beschaef/rtos#12]
The [currently used method](https://github.com/beschaef/rtos/blob/master/src/features/mod.rs#L13) is subject to fluctuations up to 15%. For a correct system behaviour we need to make the calculation to deliver much more accurate results.

**Comment by beschaef** [comment]
We have three different ways now to get the CPU frequency.
1) directly via raw_cpuid crate
2) indirecty via raw_cpuid crate from the cpu brand string
3) calculated with the PIT and tsc
