### ISSUE TITLE
Tetris Bug - Index out of bounds

### ISSUE THREAD

**Issue by beschaef** [beschaef/rtos#20]
Index out of bounds: the len is 3 but the index is 3.

![rtos_bug_tetris](https://user-images.githubusercontent.com/11885132/42081148-019ecd48-7b85-11e8-99fb-cc91335a71f5.png)

**Comment by daschwin** [comment]
Weißt du zufällig durch was dieser Fehler aufgetreten ist, damit ich ihn nachstellen kann?

**Comment by beschaef** [comment]
nee, einfach nur durchs testen
ich wollte eigentlich einen ganz anderen fehler reproduzieren...
das tritt auch nur sehr sehr selten auf
