### ISSUE TITLE
How to run it with macos

### ISSUE THREAD

**Issue by mmaechtel** [beschaef/rtos#23]
'make all' fails to compile with

"   Compiling rtos v0.1.0 (file:///Users/maechtel/Work/rtos)
error: linking with `lld` failed: exit code: 1
"

Any hints how to install the correct toolchain in macos?

**Comment by mmaechtel** [comment]
some more details:
```
= note: lld: error: undefined symbol: c_cpuid
          >>> referenced by lib.rs:61 (/Users/maechtel/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-3.1.0/src/lib.rs:61)
          >>>               raw_cpuid-1e9a67b3f5c29e23.raw_cpuid0.rcgu.o:(raw_cpuid::cpuid2::h09a469dd95af66cd) in archive /Users/maechtel/Work/rtos/target/x86_64-rtos/debug/deps/libraw_cpuid-1e9a67b3f5c29e23.rlib

          lld: error: undefined symbol: c_cpuid
          >>> referenced by lib.rs:81 (/Users/maechtel/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-3.1.0/src/lib.rs:81)
          >>>               raw_cpuid-1e9a67b3f5c29e23.raw_cpuid0.rcgu.o:(raw_cpuid::cpuid1::ha1572acf5c6b97b4) in archive /Users/maechtel/Work/rtos/target/x86_64-rtos/debug/deps/libraw_cpuid-1e9a67b3f5c29e23.rlib
```

**Comment by beschaef** [comment]
Maybe it is a problem that mac will compile it as a Mach-O file instead of an ELF.
I'm not sure, but may it could help to install the gcc cross_compiler.

**Comment by beschaef** [comment]
Currently we try to find a mac and reproduce the error.

**Comment by beschaef** [comment]
We are still not shure how to fix this, but we are in conversation with the maintainer of the crate.
We also opend an [issue](https://github.com/gz/rust-cpuid/issues/28) there.
