### ISSUE TITLE
qemu cpu typ

### ISSUE THREAD

**Issue by mmaechtel** [beschaef/rtos#24]
I run linux in a virtual machine, and kvm does therefore not work. Which cpu typ do I have to use for qemu?

**Comment by UllusParvus** [comment]
We'll take on the issue and respond as soon as we have a solution.

**Comment by UllusParvus** [comment]
@mmaechtel btw: could you provide the exact error message which is shown after you've run `make all` in your virtual machine?
Do you use VirtualBox or another virtualization tool?

**Comment by mmaechtel** [comment]
qemu starts with:
```
Booting from harddisk
Booting (first stage)
Booting (second stage)
No long mode support
```

and then nothing more ..... just hangs ....
