### ISSUE TITLE
Enhancement of scheduler

### ISSUE THREAD

**Issue by UllusParvus** [beschaef/rtos#8]
- Add a "finished" status to remove tasks for which the processing has been completed
- Add more fancy ultracool features

**Comment by beschaef** [comment]
Splitted Tasks and Scheduler

**Comment by beschaef** [comment]
added function to terminate tasks.
updated scheduler to handle tasks with status FINISHED
[commit](https://github.com/beschaef/rtos/commit/5e895894e57575bd76a6fc762383a45c173999c1)
